from esparsa import cria_posicao, eh_posicao, posicao_linha, posicao_coluna, \
           posicao_igual, posicao_str, cria_matriz, eh_matriz, \
           matriz_zero, matriz_copia, matriz_posicao, matriz_valor, \
           matriz_dimensao, matriz_densidade, matriz_nulo, matriz_str, \
           matriz_linha, matriz_coluna, matriz_diagonal

mat = cria_matriz(5)
matriz_posicao(mat, cria_posicao(1, 1), 3)
matriz_posicao(mat, cria_posicao(1, 3), 7)
matriz_posicao(mat, cria_posicao(2, 2), 4)
matriz_posicao(mat, cria_posicao(3, 1), 2)
matriz_posicao(mat, cria_posicao(3, 3), 1)
print(matriz_str(mat, "%.2f"))
print(matriz_linha(mat, 3))
print(matriz_coluna(mat, 2))
print(matriz_diagonal(mat))
print(mat)
print(matriz_posicao(mat, cria_posicao(1, 2), 4.0))
print(mat)
print(matriz_valor(mat, cria_posicao(0, 0)))
print(mat)
print(matriz_dimensao(mat))
print(matriz_str(mat, "%.1f"))
print(matriz_densidade(mat))
print(mat)
print(matriz_nulo(mat, 4))
print(mat)
print(cria_posicao(1, 1))
print(posicao_igual(cria_posicao(2, 2), (2, 2)))
print(posicao_igual(3, 3))
print(posicao_igual(cria_posicao(2, 2), cria_posicao(3, 4)))
print(eh_posicao(cria_posicao(3, 4)))
print(eh_posicao((3.0, 4.0)))
print(type(posicao_str(cria_posicao(8, 9))))
print(posicao_linha(cria_posicao(3, 6)))
print(posicao_coluna(cria_posicao(6, 1)))
print(eh_matriz(mat))
print(eh_matriz({(1, 1): 4.0, (1, 2): 7.0, (3, 1): 2.0, (3, 3): 1.0}))
print(matriz_zero(mat))
mat2 = matriz_copia(mat)
print(mat)
print(matriz_posicao(mat2, cria_posicao(2, 3), 9))
print(mat2)
print(mat)
